# Generated by Django 4.2.7 on 2025-10-25 11:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='Número único de pedido que el cliente usará para rastrear', max_length=50, unique=True, verbose_name='Número de Pedido')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Nombre del Cliente')),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del Cliente')),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del Cliente')),
                ('delivery_address', models.TextField(verbose_name='Dirección de Entrega')),
                ('delivery_city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('delivery_postal_code', models.CharField(max_length=10, verbose_name='Código Postal')),
                ('status', models.CharField(choices=[('PENDING', 'Order Received'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('current_location', models.CharField(blank=True, help_text='Ubicación actual del pedido en el proceso de entrega', max_length=200, null=True, verbose_name='Ubicación Actual')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Estimada de Entrega')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el pedido', null=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Order Received'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=20, verbose_name='Estado')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Historial de Pedido',
                'verbose_name_plural': 'Historial de Pedidos',
                'ordering': ['-timestamp'],
            },
        ),
    ]
