# Generated by Django 4.2.7 on 2025-10-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_delayed',
            field=models.BooleanField(default=False, help_text='Marcar si el pedido va con retraso en la entrega', verbose_name='Pedido con Retraso'),
        ),
    ]
